In [81]:
import tensorflow as tf 
import os
import pandas as pd
os.environ["CUDA_VISIBLE_DEVICES"]="2"


%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [9]:
cd /home/users/cdonoso/rnn_classifier/

/home/users/cdonoso/rnn_classifier


In [82]:
from core.models import get_lstm
from core.data import load_records
from core.losses import custom_bce, custom_bce_v2

In [29]:
metadata = pd.read_csv(os.path.join('./data/records/forced/fold_0/', 'test_samples.csv'))
num_classes = len(metadata['alerceclass'].unique())

train_batches = load_records(os.path.join('./data/records/forced/fold_0', 'train'),
                             256,
                             max_obs=200,
                             num_classes=num_classes,
                             sampling=False,
                             shuffle=True)

val_batches   = load_records(os.path.join('./data/records/forced/fold_0', 'val'),
                             256,
                             max_obs=200,
                             num_classes=num_classes,
                             sampling=False,
                             shuffle=False)
num_classes

16

In [30]:
model = get_lstm(256, num_classes, max_obs=200, dropout=0.2)

In [84]:
for x, y in train_batches:
    output = model(x)
    cce_0 = custom_bce_v2(y, output)
    
    cce_1 = custom_bce(y, output)
    print(cce_0)
    print(cce_1)
    break

tf.Tensor(3.3824117, shape=(), dtype=float32)
tf.Tensor(0.013219603, shape=(), dtype=float32)


2021-11-25 23:33:43.274656: W tensorflow/core/kernels/data/cache_dataset_ops.cc:768] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


In [97]:
from core.data import load_records
from astropackage.embeddings import SingleBand

In [98]:
data = load_records('/tf/classifier/astromer/data/records/macho/train', 10, max_obs=200)

In [99]:
embedding = SingleBand()

[INFO] Loading ASTROMER Embedding...


In [151]:
for batch in data:
    print(batch['values'].shape)
    magnitudes = tf.slice(batch['values'], [0,0,1], [-1,-1,1])
    times = tf.slice(batch['values'], [0,0,0], [-1,-1,1])
    mask = batch['mask']
    
    cls, reg = embedding([magnitudes, times, mask])
    print(cls.shape)
    print(reg.shape)
    print(batch['length'])
    break
    

(10, 200, 3)
(10, 640)
(10, 200, 128)
tf.Tensor([200 200 200 200 200 200 200 200 200 200], shape=(10,), dtype=int32)


In [134]:
clstkn = tf.tile(tf.cast([[[-99]]], tf.float32), [serie[0].shape[0], 1, serie[0].shape[-1]], name='cls_tkn')
clstkn.shape

TypeError: 'int' object is not subscriptable

In [129]:
dim = tf.shape(serie)
series = tf.reshape(serie, [dim[0], dim[1]*dim[2], dim[3]])

In [130]:
series[0]

<tf.Tensor: shape=(234, 1), dtype=float32, numpy=
array([[-9.9000000e+01],
       [ 4.8003569e-01],
       [-7.5382793e-01],
       [ 4.4839895e-01],
       [ 2.6806447e-01],
       [-1.8231760e+00],
       [ 3.1868538e-01],
       [ 9.0895012e-02],
       [-1.3508840e-02],
       [ 4.6421808e-01],
       [ 3.3947043e-02],
       [ 2.2377209e-01],
       [ 4.4207188e-01],
       [-1.6080413e+00],
       [-9.4997996e-01],
       [-7.9812026e-01],
       [ 4.6602648e-02],
       [ 6.7302573e-01],
       [-1.4593451e+00],
       [-2.7926451e-01],
       [ 2.5541037e-01],
       [ 2.9653922e-01],
       [-3.2988390e-01],
       [ 5.3382015e-01],
       [-1.4322241e-01],
       [-7.1817911e-03],
       [-9.1517973e-01],
       [-1.2740478e-01],
       [-9.2602991e-02],
       [ 3.7246832e-01],
       [ 5.0851041e-01],
       [-1.4846548e+00],
       [ 2.7619995e-02],
       [ 4.3208337e+00],
       [ 6.2420271e-02],
       [-2.3813568e-01],
       [-1.7567375e+00],
       [-1.3517778e+00],
